//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThisIsNotArt.Resources {
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThisIsNotArt.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US District Court, 1982
        ///
        ///America&apos;s Best Family Showplace Corp. v. City of New York, Dept. of Bldgs
        ///
        ///In no sense can it be said that video games are meant to inform. Rather, a video game, like a pinball game, a game of chess, or a game of baseball, is pure entertainment with no informational element. That some of these games &quot;talk&quot; to the participant, play music, or have written instructions does not provide the missing element of &quot;information.&quot; I find, therefore, that although video game programs may be [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Text_01 {
            get {
                return ResourceManager.GetString("Text_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US District Court, 2002
        ///
        ///Interactive Digital Software Association v. St. Louis County
        ///
        ///Just like Bingo, the Court fails to see how video games express ideas, impressions, feelings, or information unrelated to the game itself..
        /// </summary>
        public static string Text_02 {
            get {
                return ResourceManager.GetString("Text_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roger Ebert, an American film critic, historian, journalist, screenwriter, and author, 2005
        ///
        ///Why did the Chicken Cross the Genders?
        ///
        ///To my knowledge, no one in or out of the field has ever been able to cite a game worthy of comparison with the great dramatists, poets, filmmakers, novelists and composers. That a game can aspire to artistic importance as a visual experience, I accept. But for most gamers, video games represent a loss of those precious hours we have available to make ourselves more culture [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Text_03 {
            get {
                return ResourceManager.GetString("Text_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hideo Kojima, a creator of &quot;Metal Gear Solid&quot; game, 2006
        ///
        ///Games aren&apos;t art, says Kojima
        ///
        ///Art is something that radiates the artist. If 100 people walk by and a single person is captivated by whatever that piece radiates, it&apos;s art. But videogames aren&apos;t trying to capture one person. A videogame should make sure that all 100 people that play that game should enjoy the service provided by that videogame. It&apos;s something of a service. It&apos;s not art..
        /// </summary>
        public static string Text_04 {
            get {
                return ResourceManager.GetString("Text_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Lanchester, a British journalist and novelist, 2009
        ///
        ///Is it Art?
        ///
        ///Books, films, TV, dance, theatre, music, painting, photography, sculpture, all have publics which either are or aren&apos;t interested in them, but at least know that these forms exist, that things happen in them in which people who are interested in them are interested. They are all part of our current cultural discourse. Video games aren&apos;t..
        /// </summary>
        public static string Text_05 {
            get {
                return ResourceManager.GetString("Text_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tales of Tales, the creators of &quot;The Path&quot; game, 2010
        ///
        ///GAMES ARE NOT ART
        ///
        ///People have been playing games for as long as they have existed. Even animals play games. Lifeforms with brains seem to have a need for playful behaviour. Art, on the other hand is not born out of a physical need or an animal instinct. Art is born out of a desire to touch the untouchable. To explore the unknown. Or pay tribute to it. Art is born out of a desire for transcendence. There are no rules in art that cannot be broken. Th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Text_06 {
            get {
                return ResourceManager.GetString("Text_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jonathan Jones, a British art critic, 2012
        ///
        ///Sorry MoMA, video games are not art
        ///
        ///A work of art is one person&apos;s reaction to life. Any definition of art that robs it of this inner response by a human creator is a worthless definition. Art may be made with a paintbrush or selected as a ready-made, but it has to be an act of personal imagination.
        ///The worlds created by electronic games are more like playgrounds where experience is created by the interaction between a player and a programme..
        /// </summary>
        public static string Text_07 {
            get {
                return ResourceManager.GetString("Text_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Is Not Art.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://law.justia.com/cases/federal/district-courts/FSupp/536/170/2009778/.
        /// </summary>
        public static string Url_01 {
            get {
                return ResourceManager.GetString("Url_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://law.justia.com/cases/federal/district-courts/FSupp2/200/1126/2422093/.
        /// </summary>
        public static string Url_02 {
            get {
                return ResourceManager.GetString("Url_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.rogerebert.com/answer-man/why-did-the-chicken-cross-the-genders.
        /// </summary>
        public static string Url_03 {
            get {
                return ResourceManager.GetString("Url_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.eurogamer.net/articles/news240106kojimaart.
        /// </summary>
        public static string Url_04 {
            get {
                return ResourceManager.GetString("Url_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.lrb.co.uk/v31/n01/john-lanchester/is-it-art.
        /// </summary>
        public static string Url_05 {
            get {
                return ResourceManager.GetString("Url_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://youtu.be/nlep9kT1API?t=352.
        /// </summary>
        public static string Url_06 {
            get {
                return ResourceManager.GetString("Url_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.theguardian.com/artanddesign/jonathanjonesblog/2012/nov/30/moma-video-games-art.
        /// </summary>
        public static string Url_07 {
            get {
                return ResourceManager.GetString("Url_07", resourceCulture);
            }
        }
    }
}
